---

networks:
  plantee:

services:
  # plantee-db:
  #   image: postgres:latest
  #   restart: unless-stopped
  #   volumes:
  #     - "./db:/var/lib/postgresql/data"
  #   networks:
  #     - plantee
  #   env_file:
  #   - .env
  plantee:
    build: .
    ports:
      - 4000:4000
    networks:
      - plantee
    restart: unless-stopped
